In [1]:
import pandas as pd
import numpy as np

In [2]:
np.random.seed(42)
data = {
    'EmployeeID': range(101, 601),
    'Name': [f'Employee_{i}' for i in range(1, 501)],
    'Department': np.random.choice(['HR', 'IT', 'Finance', 'Marketing', 'Operations'], size=500),
    'Age': np.random.randint(22, 60, size=500),
    'Experience': np.random.randint(1, 35, size=500),
    'Salary': np.random.randint(40000, 150000, size=500),
    'PerformanceRating': np.random.choice([1, 2, 3, 4, 5], size=500),
    'RemoteWork': np.random.choice(['Yes', 'No'], size=500)
}

In [3]:
df_synthetic = pd.DataFrame(data)

In [4]:
duplicates = df_synthetic.sample(n=12, random_state=42)
df_synthetic = pd.concat([df_synthetic, duplicates], ignore_index=True)

In [5]:
df_synthetic = df_synthetic.iloc[:500].copy()

In [6]:
df_synthetic.loc[df_synthetic.sample(n=15, random_state=1).index, 'Age'] = np.nan
df_synthetic.loc[df_synthetic.sample(n=25, random_state=2).index, 'Salary'] = np.nan

In [7]:
df_synthetic.to_csv('employee_salary.csv', index=False)

In [8]:
df = pd.read_csv('employee_salary.csv')

In [9]:
df.shape

(500, 8)

In [10]:
df.head()

,EmployeeID,Name,Department,Age,Experience,Salary,PerformanceRating,RemoteWork
0,101,Employee_1,Marketing,41.0,9,75488.0,5,No
1,102,Employee_2,Operations,46.0,9,NaN,2,Yes
2,103,Employee_3,Finance,43.0,10,114663.0,3,Yes
3,104,Employee_4,Operations,34.0,26,62431.0,2,No
4,105,Employee_5,Operations,40.0,25,101681.0,5,Yes

In [12]:
df.tail()

,EmployeeID,Name,Department,Age,Experience,Salary,PerformanceRating,RemoteWork
495,596,Employee_496,HR,57.0,15,47421.0,2,No
496,597,Employee_497,Finance,44.0,16,126936.0,5,No
497,598,Employee_498,HR,22.0,22,139073.0,4,Yes
498,599,Employee_499,HR,36.0,28,57727.0,2,Yes
499,600,Employee_500,HR,42.0,20,44358.0,4,No

In [13]:
df.columns

Index(['EmployeeID', 'Name', 'Department', 'Age', 'Experience', 'Salary',
       'PerformanceRating', 'RemoteWork'],
      dtype='object')

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   EmployeeID         500 non-null    int64
 1   Name               500 non-null    object
 2   Department         500 non-null    object
 3   Age                485 non-null    float64
 4   Experience         500 non-null    int64
 5   Salary             475 non-null    float64
 6   PerformanceRating  500 non-null    int64
 7   RemoteWork         500 non-null    object
dtypes: float64(2), int64(3), object(3)
memory usage: 31.4+ KB

In [15]:
df.describe()

       EmployeeID         Age  Experience         Salary  PerformanceRating
count  500.000000  485.000000  500.000000     475.000000         500.000000
mean   350.500000   40.632990   18.352000   95974.555789           3.112000
std    144.481833   11.195361    9.745051   32380.138931           1.422499
min    101.000000   22.000000    1.000000   40281.000000           1.000000
25%    225.750000   31.000000   10.000000   67210.500000           2.000000
50%    350.500000   41.000000   18.000000   95826.000000           3.000000
75%    475.250000   50.000000   27.000000  123252.000000           4.000000
max    600.000000   59.000000   34.000000  149326.000000           5.000000

In [16]:
df.isnull().sum()

EmployeeID            0
Name                  0
Department            0
Age                  15
Experience            0
Salary               25
PerformanceRating     0
RemoteWork            0
dtype: int64

In [17]:
(df.isnull().sum() / len(df)) * 100

EmployeeID           0.0
Name                 0.0
Department           0.0
Age                  3.0
Experience           0.0
Salary               5.0
PerformanceRating    0.0
RemoteWork           0.0
dtype: float64

In [18]:
df.duplicated().sum()

np.int64(0)

In [21]:
len(df)

500

In [23]:
df_cleaned = df.drop_duplicates()
#No need of executing this command because there are no duplicate values

In [24]:
len(df_cleaned)

500